"""The vanilla prototype table, as distilled from Factorio 1.1's `data.raw`.

Every size, speed and recipe used anywhere in this harness comes through here.
Nothing is hard-coded from memory: `assets/prototypes.json` is generated by
`tools/distill_data_raw.py` and carries the sha256 of the dump it came from.
"""

from __future__ import annotations

import functools
import json
import pathlib
from dataclasses import dataclass

ASSETS = pathlib.Path(__file__).resolve().parents[2] / "assets"
TABLE = ASSETS / "prototypes.json"

# Factorio 1.1 directions. 0 is north and the numbers run clockwise; the odd
# values are only reachable by rails, but they are kept in the vocabulary so a
# scraped rail blueprint round-trips instead of being dropped.
NORTH, NORTHEAST, EAST, SOUTHEAST, SOUTH, SOUTHWEST, WEST, NORTHWEST = range(8)
DIRECTIONS = tuple(range(8))

# One game tick is 1/60 s and belt `speed` is in tiles per tick, with items
# spaced every 0.25 tiles on two lanes: 0.03125 * 60 / 0.25 * 2 = 15 items/s for
# a yellow belt, which is the number the wiki quotes.
TICKS_PER_SECOND = 60
ITEMS_PER_TILE = 4


@dataclass(frozen=True)
class Entity:
    """A placeable prototype, reduced to what blueprint geometry needs."""

    name: str
    category: str
    width: int
    height: int
    color: str
    takes_recipe: bool
    crafting_speed: float | None = None
    crafting_categories: tuple[str, ...] = ()
    speed: float | None = None
    mining_speed: float | None = None
    supply_area: float | None = None
    wire_distance: float | None = None
    max_distance: float | None = None
    energy_usage: float | None = None
    module_slots: int = 0

    def footprint(self, direction: int = NORTH) -> tuple[int, int]:
        """Tiles occupied, accounting for rotation.

        Turning a splitter east makes it 1x2 rather than 2x1. Square entities —
        which is most of them — are unaffected, and this is the one place that
        distinction lives.
        """
        if direction in (EAST, WEST) and self.width != self.height:
            return self.height, self.width
        return self.width, self.height

    @property
    def takes_flow(self) -> bool:
        """Whether the blueprint JSON carries a `type: input|output` for this.

        Underground belts are the only vanilla case that matters here, and it is
        the field, not the direction, that decides which end is the exit: both
        halves of a pair share one direction. Getting this wrong produces
        blueprints that look right in a renderer and move nothing in the game.
        """
        return self.category == "underground-belt"

    def items_per_second(self) -> float | None:
        """Throughput of a belt-like prototype, in items per second."""
        if self.speed is None or self.category not in {
            "transport-belt",
            "underground-belt",
            "splitter",
        }:
            return None
        return self.speed * TICKS_PER_SECOND * ITEMS_PER_TILE * 2


@dataclass(frozen=True)
class Recipe:
    name: str
    category: str
    time: float
    ingredients: tuple[tuple[str, float], ...]
    results: tuple[tuple[str, float], ...]

    def yields(self, item: str) -> float:
        return next((amount for name, amount in self.results if name == item), 0.0)


@dataclass(frozen=True, eq=False)
class Data:
    """The whole table. Compared and hashed by identity.

    Field-wise equality would have to hash the dicts inside, which throws, and
    `load` hands out one shared instance anyway — so identity is both the
    cheaper and the truer answer, and it lets `functools.cache` key on it.
    """

    provenance: dict
    entities: dict[str, Entity]
    recipes: dict[str, Recipe]
    stack_sizes: dict[str, int]

    def entity(self, name: str) -> Entity | None:
        return self.entities.get(name)

    @functools.cache  # noqa: B019 - `load` hands out one instance for the process
    def crafters_for(self, recipe: Recipe) -> tuple[Entity, ...]:
        """Machines that can run `recipe`, fastest last.

        Ties break by name so the list is stable across runs; the planner picks
        by explicit tier rather than by trusting this order.
        """
        able = [
            entity
            for entity in self.entities.values()
            if recipe.category in entity.crafting_categories
        ]
        return tuple(sorted(able, key=lambda entity: (entity.crafting_speed or 0.0, entity.name)))

    @functools.cache  # noqa: B019 - see `crafters_for`
    def producers_of(self, item: str) -> tuple[Recipe, ...]:
        """Recipes yielding `item`, cheapest first by ingredient count.

        Oil products have several routes; preferring the shortest ingredient
        list picks basic over advanced processing, which is what a starter base
        wants and what the planner documents as its bias.

        Cached, and returning a tuple so that caching is safe: this is a full
        scan of the recipe table, `plan.solve` walks a crafting tree calling it
        at every node, and the module generator solves a tree per draw. Without
        the cache it is the single most expensive thing in a corpus build.
        """
        made = [recipe for recipe in self.recipes.values() if recipe.yields(item) > 0]
        return tuple(sorted(made, key=lambda recipe: (len(recipe.ingredients), recipe.name)))


@functools.cache
def load(path: pathlib.Path | None = None) -> Data:
    """Read the distilled table. Cached: it is immutable and read everywhere."""
    blob = json.loads((path or TABLE).read_text())
    entities = {
        name: Entity(
            name=name,
            category=body["category"],
            width=body["width"],
            height=body["height"],
            color=body["color"],
            takes_recipe=body["takes_recipe"],
            crafting_speed=body.get("crafting_speed"),
            crafting_categories=tuple(body.get("crafting_categories", ())),
            speed=body.get("speed"),
            mining_speed=body.get("mining_speed"),
            supply_area=body.get("supply_area"),
            wire_distance=body.get("wire_distance"),
            max_distance=body.get("max_distance"),
            energy_usage=body.get("energy_usage"),
            module_slots=body.get("module_slots", 0),
        )
        for name, body in blob["entities"].items()
    }
    recipes = {
        name: Recipe(
            name=name,
            category=body["category"],
            time=body["time"],
            ingredients=tuple((part["name"], part["amount"]) for part in body["ingredients"]),
            results=tuple((part["name"], part["amount"]) for part in body["results"]),
        )
        for name, body in blob["recipes"].items()
    }
    return Data(
        provenance=blob["provenance"],
        entities=entities,
        recipes=recipes,
        stack_sizes={name: body["stack_size"] for name, body in blob.get("items", {}).items()},
    )
